#!/bin/bash

user_name="user"

if [[ -z "${1+set}" ]]; then
    /usr/bin/firejail --rmenv=HOME --env=USER="$user_name" zoom
else
    /usr/bin/firejail --rmenv=HOME --env=USER="$user_name" zoom "$1"
fi